[project]
name = "sus-mortality-pipeline"
version = "1.0.0"
description = "SUS Mortality Data Pipeline - Download, process and analyze Brazilian SUS mortality data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.30.0",
    "pysus>=1.0.0",
    "requests>=2.25.0",
    "tqdm>=4.64.0",
]